version: '3.8'

services:
  # MySQL 설정
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # 루트 비밀번호
      MYSQL_DATABASE: bizportal    # 초기 생성 데이터베이스
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  # MongoDB 설정
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  # Redis 설정
  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.5
    container_name: my_weaviate
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"

      # ✅ 임베딩은 너 FastAPI에서 만들 거라서 벡터라이저 비활성화
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""

      # ✅ 일단 연결 확인용(개발) 익명 접근 허용
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
    volumes:
      - ./weaviate_data:/var/lib/weaviate



  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: my_elasticsearch
    restart: always
    # 실행될 때 플러그인을 설치하고 ES를 실행하도록 명령어를 변경
    command: >
      sh -c "elasticsearch-plugin install --batch analysis-nori && /usr/local/bin/docker-entrypoint.sh"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data