server:
  port: 8090
  forward-headers-strategy: native

spring:
  datasource:
    url: ${DB_PROD_URL:}
    username: ${DB_PROD_USER:}
    password: ${DB_PROD_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mongodb:
    uri: mongodb+srv://admin_jiyoung:e54IPSQk67KQtAp5@bizportal-chat.mltsgbs.mongodb.net/bizchat?retryWrites=true&w=majority&appName=bizportal-chat&authSource=admin

  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}

logging:
  level:
    root: INFO

# ===== AWS / S3 (운영: 로컬 저장 안 함, S3 presigned만 사용) =====
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
    region:
      static: us-west-1
    stack:
      auto: false

app:
  cookie:
    secure: true

  s3:
    bucket: ${AWS_BUCKET:}
    region: us-west-1
    env: prod

  elasticsearch:
    host: ${ELASTIC_HOST:}
    index-search-alias: bizportal_search
    index-menu-alias: bizportal_search_menu

  search:
    outbox:
      fixed-delay-ms: 1000

# 네 ConfigMap에 있으니 그대로 매핑됨
ai:
  fastapi:
    base-url: ${AI_FASTAPI_BASE_URL:}
    callback-secret: ${AI_FASTAPI_CALLBACK_SECRET:}

internal:
  ai:
    callback-header: ${INTERNAL_AI_CALLBACK_HEADER:}
    callback-key: ${INTERNAL_AI_CALLBACK_KEY:}

    prov:
      callback_url: ${INTERNAL_AI_PROV_CALLBACK_URL:}

    meetings:
      callback-url: ${INTERNAL_AI_MEETINGS_CALLBACK_URL:}
    chatbot:
      callback-url: ${INTERNAL_AI_CHATBOT_CALLBACK_URL:}

holiday:
  service-key: ${HOLIDAY_SERVICE_KEY:}

nts:
  api:
    service-key: ${NTS_API_SERVICE_KEY:}

juso:
  api:
    key: ${JUSO_API_KEY:}
    return-url: "https://bizportal.pro/auth/juso/popup"

portone:
  api-key: ${PORTONE_API_KEY:}
  api-secret: ${PORTONE_API_SECRET:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
  health:
    defaults:
      enabled: false
    mongo:
      enabled: false
    elasticsearch:
      enabled: false

aws:
  access-key: ${AWS_ACCESS_KEY_ID:}
  secret-key: ${AWS_SECRET_ACCESS_KEY:}
  region: us-west-1

document:
  openai:
    api:
      key: ${OPENAI_KEY}
      url: https://api.openai.com/v1/chat/completions
      model: gpt-4o-mini
      max-tokens: 150
      temperature: 0.3




