spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
    com.multi.mlpenterpriseapprovalsystem: DEBUG
    org.springframework.security: DEBUG

    #     JDBC 실행 로그 너무길어서 안보고싶으면끔
    jdbc:
      resultset: OFF
      audit: OFF
      connection: OFF
