server:
  port: 8090

spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 1000MB     # 개별 파일의 최대 크기
      max-request-size: 1000MB  # 한 번의 요청(여러 파일 포함 가능)의 총 최대 크기


openai:
  api-key: ${OPENAI_KEY}
  gpt4o-url: https://api.openai.com/v1/chat/completions
  image-url: https://api.openai.com/v1/images/generations


file:
  upload-dir:
  resource-handler:
  resource-locations: file:${file.upload-dir}

springdoc:
  group-configs:
    - group: all
      paths-to-match: /**
---
spring:
  config:
    activate:
      on-profile: local, test
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.multi.restproduct: DEBUG
    org.springframework.security: DEBUG

    #     JDBC 실행 로그 너무길어서 안보고싶으면끔
    jdbc:
      resultset: OFF
      audit: OFF
      connection: OFF

---


#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    url: jdbc:mysql://localhost:3306/bizportal
#    username: ${DB_PROD_USER}
#    password: ${DB_PROD_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB
#
#
#logging:
#  level:
#    root: INFO
#    com.multi.restproduct: INFO