apiVersion: v1
kind: Secret
metadata:
  name: bizportal-secrets
  namespace: bizportal
type: Opaque
data:
  DB_PROD_PASSWORD: bXlzcWwxMjM0
  DB_PROD_URL: amRiYzpteXNxbDovL3NhbXBsZS1yZHMuYzZsYmtibG9jMjRxLnVzLXdlc3QtMS5yZHMuYW1hem9uYXdzLmNvbTozMzA2L2JpenBvcnRhbD9zZXJ2ZXJUaW1lem9uZT1Bc2lhL1Nlb3VsJmNoYXJhY3RlckVuY29kaW5nPVVURi04JnVzZVNTTD1mYWxzZQ==
  DB_PROD_USER: cm9vdA==
  HOLIDAY_SERVICE_KEY: MmIwOTIyZjdkMzcxZmUyOTIwYTFlZTM5ZDAxNTBiOGE3YmQ1ZGNmYmRjOWM4OGViZWEwMWI5YmE5NGJjM2JhNQ==
  JUSO_API_KEY: ZGV2VTAxVFgwRlZWRWd5TURJMU1USXlNVEV6TkRReE16RXhOalU1TURZPQ==
  JWT_ISSUER: VEVTVEBURVNULkNPTQ==
  JWT_SECRET: OGZ3blJrOGRxYWovR3ErTU1SL3ArdWRXTXA2UjVwOTZ5bWhZNmFKeitmeHNkQVQ4NVdEZ3NybFBucmtka3FLUWU0ZU1lb2w1VnEwV0pnenJxemJIV0E9PQ==
  NTS_API_SERVICE_KEY: MmIwOTIyZjdkMzcxZmUyOTIwYTFlZTM5ZDAxNTBiOGE3YmQ1ZGNmYmRjOWM4OGViZWEwMWI5YmE5NGJjM2JhNQ==