apiVersion: v1
kind: ConfigMap
metadata:
  name: bizportal-config
  namespace: bizportal
data:
  SPRING_PROFILES_ACTIVE: "prod"
  AWS_BUCKET: "to-bizportal-us"
  SPRING_DATA_MONGODB_URI: "mongodb+srv://admin_jiyoung:Unv1Ghh3ApWUdIB6@bizportal-chat.mltsgbs.mongodb.net/bizchat?retryWrites=true&w=majority&appName=bizportal-chat"
  REDIS_HOST: "bizportal-redis.tlfhdn.ng.0001.usw1.cache.amazonaws.com"
  REDIS_PORT: "6379"
  ELASTIC_HOST: "http://elasticsearch.bizportal.svc.cluster.local:9200"
  WEAVIATE_HTTP_URL: "http://weaviate.bizportal.svc.cluster.local:8080"
  WEAVIATE_URL: "http://weaviate.bizportal.svc.cluster.local:8080"
  AI_FASTAPI_BASE_URL: "http://bizportal-fastapi.bizportal.svc.cluster.local:8000"
  INTERNAL_AI_CALLBACK_HEADER: "X-Internal-Callback-Key"
  INTERNAL_AI_MEETINGS_CALLBACK_URL: "http://bizportal-api-svc.bizportal.svc.cluster.local/api/v1/meetings/%d/ai"
  INTERNAL_AI_CHATBOT_CALLBACK_URL: "http://bizportal-api-svc.bizportal.svc.cluster.local/api/v1/chatbot/callback"